# Generated by Django 3.0.2 on 2022-02-19 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploaded_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='uploaded_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
