# Generated by Django 3.0.2 on 2022-02-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0002_uploaded_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded',
            name='uploaded_by',
        ),
    ]
