# Generated by Django 3.0.2 on 2022-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0003_remove_uploaded_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
