# Generated by Django 3.0.2 on 2022-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0004_uploaded_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
