# Generated by Django 3.0.2 on 2022-02-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0005_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
