# Generated by Django 3.0.2 on 2022-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0006_uploaded_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
