# Generated by Django 3.0.2 on 2022-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0008_auto_20220219_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
