# Generated by Django 3.0.2 on 2022-02-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0009_auto_20220219_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded',
            name='profile_image',
        ),
    ]
