# Generated by Django 3.0.2 on 2022-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0010_remove_uploaded_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to=''),
        ),
    ]
