# Generated by Django 3.0.2 on 2022-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_files', '0011_uploaded_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
