# Generated by Django 3.0.2 on 2022-02-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220218_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_producer',
        ),
    ]
