# Generated by Django 3.0.2 on 2022-02-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_customuser_is_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_producer',
        ),
    ]
