# Generated by Django 3.0.2 on 2022-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_customuser_is_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
