# Generated by Django 3.0.2 on 2022-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20220218_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
