# Generated by Django 3.0.2 on 2022-02-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_userprofile_lado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lado_id',
        ),
    ]
