# Generated by Django 3.0.2 on 2022-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_userprofile_lado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
