# Generated by Django 3.0.2 on 2022-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_userprofile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_id',
        ),
    ]
