# Generated by Django 4.0.1 on 2022-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_confirm_password', models.CharField(max_length=100)),
                ('user_country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
    ]
